### ISSUE TITLE
Bạn có thể thêm vài tính năng nữa không?

### ISSUE THREAD

**Issue by xitobg** [uchindev/zingmp3-fe-ts#3]
Tôi đã chạy thử code bên bên vercell.app khá ổn. Tuy nhiên có một số ý kiến như sau
- Hỗ trợ responsive
- Themes giống như code (https://github.com/xiaosasori/vite-zingmp3) thì tốt 
- top100
- newsong
- Chart
- BXH
- Thể loại bài hát

**Comment by uchinx** [comment]
hi @xitobg, cảm ơn bạn đã quan tâm, project này chỉ là code phần frontend thôi và nó phụ thuộc khá nhiều vào API của zingmp3 (cũng khá bất ngờ vì tới giờ nó vẫn còn chạy được), việc phát triển thêm tính năng có nhiều rủi ro vì đang phụ thuộc vào bên thứ 3, với lại mình cũng không có ý định clone thêm gì hết tại cũng không có thời gian nhiều, nếu làm thì mình sẽ build 1 project mới, tự thiết kế giao diện và build API riêng,...
BTW, bạn có thể tìm hiểu thêm các tính năng khác ở repo này, mình thấy nó khá hay: https://github.com/qier222/YesPlayMusic
